#!/bin/sh
. $(dirname $0)/Env
docker run --name=consul00 $ports -d $image_name ./consul agent -server -bootstrap-expect=3 -data-dir=/consul/data -config-dir=/consul/conf.d
masterip=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' consul00) || exit $?
docker run $ports -d $image_name ./consul agent -data-dir=/consul/data -config-dir=/consul/conf.d -join=${masterip}
docker run $ports -d $image_name ./consul agent -data-dir=/consul/data -config-dir=/consul/conf.d -join=${masterip}
docker run $ports -d $image_name ./consul agent -data-dir=/consul/data -config-dir=/consul/conf.d -join=${masterip}
